### ISSUE TITLE
Install Drupal on a subdirectory

### ISSUE THREAD

**Issue by mferraro** [wodby/drupal-php#16]
Reading the FAQs and documentation I don't find how install Drupal on a subdirectory

Example:
domain.com/**drupal**/
I need to define a basePath different then "/"

**Comment by PavelPrischepa** [comment]
You shoukd define env vars `PHP_DOCROOT` and `NGINX_DOCROOT`. Something like that:
```
php:
    environment:
        PHP_DOCROOT: drupal

nginx:
    environment:
        NGINX_DOCROOT: drupal
```
