### ISSUE TITLE
Document SSH access configuration

### ISSUE THREAD

**Issue by Vacilando** [wodby/drupal-php#38]
Please document docker-compose.yml configuration to access the PHP container via SSH.
Perhaps best would be to add it as a commented section in docker-compose.yml itself.

Something like this works for me (inspired by https://github.com/wodby/docker4drupal/issues/65#issuecomment-288293006):
```
  sshd:
    image: wodby/drupal-php:7.1-2.1.0
    command: /usr/sbin/sshd -De
    environment:
      SSH_PUBLIC_KEYS: |-
        ["MYKEY"]
    volumes:
      - ./:/var/www/html
    ports:
      - '2222:22'
```

**Comment by Vacilando** [comment]
Drush did not work when using drupal-php versions with stability tags -- see #39 

Here's an updated snippet that works:
```
  sshd:
    image: wodby/drupal-php:7.1
    command: /usr/sbin/sshd -De
    environment:
      SSH_PUBLIC_KEYS: |-
        ["MYKEY"]
    volumes:
      - ./:/var/www/html
    ports:
      - '2222:22'
```
