### ISSUE TITLE
Cannot pass variables in from docker-compose

### ISSUE THREAD

**Issue by ohthehugemanatee** [wodby/drupal-php#44]
I use environment variables for sensitive data. For example, my database username and password in settings.php simply use `getenv('DB_USERNAME')` and `getenv('DB_PASSWORD')` . I also have a variable that indicates the environment (local/dev/stage/live).

I recently switched from wodby php 7.0 to 7.1 . With 7.0 I configured those environment variables in docker.compose:

```
  php:
    image: wodby/drupal-php:7.0
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
      ENVIRONMENT: localdev
      PHP_XDEBUG: 1
    volumes:
      - .:/var/www/html
```

In 7.1, this no longer works. Those environment variables are set for root, but php runs as www-data, and doesn't get those vars.

What's the recommended way to pass in environment-specific values with the current version?
