### ISSUE TITLE
Start with xdebug disabled

### ISSUE THREAD

**Issue by claudiu-cristea** [wodby/drupal-php#92]
My `php` service:

```
  php:
    image: wodby/drupal-php:8.1
    environment:
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
      PHP_XDEBUG: 0
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
      PHP_FPM_CLEAR_ENV: "no"
      PHP_OPCACHE_PRELOAD_USER: wodby
      PHP_XDEBUG_DEFAULT_ENABLE: 0
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 1
      PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"
      PHP_XDEBUG_IDEKEY: "PHPSTORM"
      PHP_IDE_CONFIG: "serverName=drupalextension"
    volumes:
      - ./:/var/www/html
```

But when bring the container up, XDebug is enabled. I'm expecting to be disabled
